# Generated by Django 5.2.11 on 2026-02-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Город')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткое имя')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Полное имя')),
            ],
            options={
                'verbose_name': 'Код',
                'verbose_name_plural': 'Список кодов',
                'ordering': ['code'],
            },
        ),
    ]
